#define MOB_VNUM_DEMON_FIRST		201
#define MOB_VNUM_LESSER_IMPSAGE		201
#define MOB_VNUM_VAKALIC_IMP		202
#define MOB_VNUM_FILCHLING		203
#define MOB_VNUM_POISONOUS_NJITH	204

#define MOB_VNUM_LESSER_BOUND_FIRST	210
#define MOB_VNUM_LESSER_ORZUB		210
#define MOB_VNUM_LESSER_DJAZITH		211
#define MOB_VNUM_LESSER_KURLAAC		212
#define MOB_VNUM_LESSER_QWABLITH	213
#define MOB_VNUM_LESSER_GHARKU		214
#define MOB_VNUM_LESSER_WORM		215
#define MOB_VNUM_LESSER_DEVOURING	216
#define MOB_VNUM_LESSER_ETHEREAL	217
#define MOB_VNUM_LESSER_BOUND_LAST	217

#define MOB_VNUM_DEMON_ACOLYTE		221
#define MOB_VNUM_DEMON_HOUND		222
#define MOB_VNUM_DEMON_DOPPELGANGER	223
#define MOB_VNUM_DEMON_FLIES		260

#define MOB_VNUM_NORMAL_BOUND_FIRST	231
#define MOB_VNUM_DEMON_WVERSHAK		231
#define MOB_VNUM_DEMON_NVAEGRA		232
#define MOB_VNUM_DEMON_KHILMESTAHN	233
#define MOB_VNUM_DEMON_SPAWN		234
#define MOB_VNUM_DEMON_SERVITOR		235
#define MOB_VNUM_DEMON_HORROR		236
#define MOB_VNUM_DEMON_SUCCUBUS		237
#define MOB_VNUM_DEMON_GUARDIAN		238
#define MOB_VNUM_NORMAL_BOUND_LAST	238

#define MOB_VNUM_GREATER_WORM		241
#define MOB_VNUM_GREATER_AGDUK		242
#define MOB_VNUM_GREATER_BARKJA		243
#define MOB_VNUM_GREATER_SAPLING	244

#define MOB_VNUM_GREATER_PRICINA	246
#define MOB_VNUM_GREATER_VAESHIR	247

#define MOB_VNUM_GREATER_BOUND_FIRST	251
#define MOB_VNUM_GREATER_WARRIOR	251
#define MOB_VNUM_GREATER_TASKMASTER	252
#define MOB_VNUM_GREATER_SYNDIC		253
#define MOB_VNUM_GREATER_UNCLEAN	254
#define MOB_VNUM_GREATER_AVATAR		255
#define MOB_VNUM_GREATER_HANDMAIDEN	256
#define MOB_VNUM_GREATER_ARCHON		257
#define MOB_VNUM_GREATER_ALIEN		258
#define MOB_VNUM_GREATER_BOUND_LAST	258
#define MOB_VNUM_DEMON_LAST		258
