 /***************************************************************************
 *  Original Diku Mud copyright (C) 1990, 1991 by Sebastian Hammer,	   *
 *  Michael Seifert, Hans Henrik St{rfeldt, Tom Madsen, and Katja Nyboe.   *
 *									   *
 *  Merc Diku Mud improvments copyright (C) 1992, 1993 by Michael	   *
 *  Chastain, Michael Quan, and Mitchell Tse.				   *
 *									   *
 *  In order to use any part of this Merc Diku Mud, you must comply with   *
 *  both the original Diku license in 'license.doc' as well the Merc	   *
 *  license in 'license.txt'.  In particular, you may not remove either of *
 *  these copyright notices.						   *
 *									   *
 *  Much time and thought has gone into this software and you are	   *
 *  benefitting.  We hope that you share your changes too.  What goes	   *
 *  around, comes around.						   *
 ***************************************************************************/
 
/***************************************************************************
*	ROM 2.4 is copyright 1993-1996 Russ Taylor			   *
*	ROM has been brought to you by the ROM consortium		   *
*	    Russ Taylor (rtaylor@efn.org)				   *
*	    Gabrielle Taylor						   *
*	    Brian Moore (zump@rom.org)					   *
*	By using this code, you have agreed to follow the terms of the	   *
*	ROM license, in the file Rom24/doc/rom.license			   *
***************************************************************************/

/* this is a listing of all the commands and command related data */

/* for command types */
#define ML 	MAX_LEVEL	/* implementor */
#define L1	MAX_LEVEL - 1  	/* creator */
#define L2	MAX_LEVEL - 2	/* supreme being */
#define L3	MAX_LEVEL - 3	/* deity */
#define L4 	MAX_LEVEL - 4	/* god */
#define L5	MAX_LEVEL - 5	/* immortal */
#define L6	MAX_LEVEL - 6	/* demigod */
#define L7	MAX_LEVEL - 7	/* angel */
#define L8	MAX_LEVEL - 8	/* avatar */
#define IM	LEVEL_IMMORTAL 	/* avatar */
#define HE	LEVEL_HERO	/* hero */

#define COM_INGORE	1


/*
 * Structure for a command in the command lookup table.
 */
struct	cmd_type
{
    char * const	name;
    DO_FUN *		do_fun;
    PRO_FUN *           prog_fun;
    int		position;
    int		level;
    int		log;
    int              show;
    int		canhide;
    int		info;
    int		canmount;
    int		comm;
    OBJ_DO_FUN * obj_do_fun;
};

/* the command table itself */
extern	const	struct	cmd_type	cmd_table	[];

/*
 * Command functions.
 * Defined in act_*.c (mostly).  <-- this is no longer true
 */

DECLARE_DO_FUN( do_bloodsigil   );
DECLARE_DO_FUN( do_listherbs	);
DECLARE_DO_FUN( do_warpath	);
DECLARE_DO_FUN(	do_rumors	);
DECLARE_DO_FUN(	do_rumormod	);
DECLARE_DO_FUN( do_rumoradd	);
DECLARE_DO_FUN( do_rush		);
DECLARE_DO_FUN( do_dash		);
DECLARE_DO_FUN( do_extraspam	);
DECLARE_DO_FUN( do_autotracks	);
DECLARE_DO_FUN( do_pursuit	);
DECLARE_DO_FUN(	do_distract	);
DECLARE_DO_FUN( do_bounty	);
DECLARE_DO_FUN( do_autopeek	);
DECLARE_DO_FUN( do_autooath	);
DECLARE_DO_FUN( do_disfigure	);
DECLARE_DO_FUN( do_froststrike	);
DECLARE_DO_FUN( do_healingward  );
DECLARE_DO_FUN( do_disruption	);
DECLARE_DO_FUN( do_rob		);
DECLARE_DO_FUN( do_headbutt	);
DECLARE_DO_FUN( do_jab		);
DECLARE_DO_FUN( do_ready	);
DECLARE_DO_FUN( do_cook		);
DECLARE_DO_FUN( do_predatoryattack);
DECLARE_DO_FUN( do_pounce	);
DECLARE_DO_FUN( do_huntersense	);
DECLARE_DO_FUN( do_bandarrow	);
DECLARE_DO_FUN( do_fletch	);
DECLARE_DO_FUN( do_forage	);
DECLARE_DO_FUN( do_thunderstrike);
DECLARE_DO_FUN( do_shielddisarm	);
DECLARE_DO_FUN( do_taunt	);
DECLARE_DO_FUN( do_endure	);
DECLARE_DO_FUN( do_enthusiasm	);
DECLARE_DO_FUN( do_bravado	);
DECLARE_DO_FUN( do_charge	);
DECLARE_DO_FUN( do_whirl	);
DECLARE_DO_FUN( do_shadowstrike	);
DECLARE_DO_FUN( do_medstrike	);
DECLARE_DO_FUN( do_immtime      );
DECLARE_DO_FUN( do_demonic_focus);
DECLARE_DO_FUN( do_demonic_might);
DECLARE_DO_FUN( do_dark_insight );
DECLARE_DO_FUN( do_abilities	);
DECLARE_DO_FUN( do_accept	);
DECLARE_DO_FUN( do_acctdata	);
DECLARE_DO_FUN( do_acctinfo	);
DECLARE_DO_FUN( do_acctpwd	);
DECLARE_DO_FUN( do_aclist	);
DECLARE_DO_FUN(	do_advance	);
DECLARE_DO_FUN( do_affects	);
DECLARE_DO_FUN( do_afk		);
DECLARE_DO_FUN(	do_agecho	);
DECLARE_DO_FUN( do_alia		);
DECLARE_DO_FUN( do_alias	);
DECLARE_DO_FUN( do_alinks	);
DECLARE_DO_FUN(	do_allow	);
DECLARE_DO_FUN( do_answer	);
DECLARE_DO_FUN( do_appraise	);
DECLARE_DO_FUN(	do_areas	);
DECLARE_DO_FUN( do_astrip       );
DECLARE_DO_FUN(	do_at		);
DECLARE_DO_FUN(	do_auction	);
DECLARE_DO_FUN( do_autoattack	);
DECLARE_DO_FUN( do_autodefend	);
DECLARE_DO_FUN( do_autoassist	);
DECLARE_DO_FUN( do_showlines);
DECLARE_DO_FUN( do_autodate	);
DECLARE_DO_FUN( do_autoexit	);
DECLARE_DO_FUN( do_autogold	);
DECLARE_DO_FUN( do_autolist	);
DECLARE_DO_FUN( do_epshow	);
DECLARE_DO_FUN( do_autoloot	);
DECLARE_DO_FUN( do_autodestroy	);
DECLARE_DO_FUN( do_autosplit	);
DECLARE_DO_FUN( do_award	);
DECLARE_DO_FUN(	do_backstab	);
DECLARE_DO_FUN( do_ignite       );
DECLARE_DO_FUN(	do_stab		);
DECLARE_DO_FUN(	do_circle	);
DECLARE_DO_FUN( do_background   );
DECLARE_DO_FUN( do_balance	);
DECLARE_DO_FUN(	do_bamfin	);
DECLARE_DO_FUN(	do_bamfout	);
DECLARE_DO_FUN(	do_ban		);
DECLARE_DO_FUN( do_bash		);
DECLARE_DO_FUN( do_muffle	);
DECLARE_DO_FUN( do_beg		);
DECLARE_DO_FUN( do_berserk	);
/*DECLARE_DO_FUN( do_bite		);*/
DECLARE_DO_FUN( do_bleed	);
DECLARE_DO_FUN( do_brand	);
DECLARE_DO_FUN(	do_brandish	);
DECLARE_DO_FUN(	do_disbelieve	);
DECLARE_DO_FUN( do_brief	);
DECLARE_DO_FUN( do_bsnoop	);
DECLARE_DO_FUN(	do_bug		);
DECLARE_DO_FUN(	do_buy		);
DECLARE_DO_FUN(	do_cast		);
DECLARE_DO_FUN(	do_assume		);
DECLARE_DO_FUN( do_castalign	);
DECLARE_DO_FUN( do_changes	);
DECLARE_DO_FUN( do_channels	);
DECLARE_DO_FUN( do_checkfollow	);
DECLARE_DO_FUN( do_chess	);
DECLARE_DO_FUN( do_clone	);
DECLARE_DO_FUN(	do_close	);
DECLARE_DO_FUN( do_convert	);
DECLARE_DO_FUN( do_cower	);
DECLARE_DO_FUN( do_colour       );	/* Colour Command By Lope */
DECLARE_DO_FUN( do_display      );
DECLARE_DO_FUN( do_sounds       );
DECLARE_DO_FUN( do_coloretto	);
DECLARE_DO_FUN( do_command	);
DECLARE_DO_FUN(	do_commands	);
DECLARE_DO_FUN( do_combine	);
DECLARE_DO_FUN( do_compact	);
DECLARE_DO_FUN(	do_compare	);
DECLARE_DO_FUN(	do_consider	);
DECLARE_DO_FUN( do_count	);
DECLARE_DO_FUN( do_shadowmastery);
DECLARE_DO_FUN(	do_credits	);
DECLARE_DO_FUN(	do_data 	);
DECLARE_DO_FUN( do_deaf		);
DECLARE_DO_FUN( do_debone	);
DECLARE_DO_FUN( do_debug	);
DECLARE_DO_FUN( do_delet	);
DECLARE_DO_FUN( do_delete	);
DECLARE_DO_FUN(	do_deny		);
DECLARE_DO_FUN( do_deposit	);
DECLARE_DO_FUN(	do_description	);
DECLARE_DO_FUN( do_destroy	);
DECLARE_DO_FUN( do_dirt		);
DECLARE_DO_FUN(	do_disarm	);
DECLARE_DO_FUN(	do_disconnect	);
DECLARE_DO_FUN( do_dismount	);
DECLARE_DO_FUN(	do_down		);
DECLARE_DO_FUN(	do_drink	);
DECLARE_DO_FUN(	do_drop		);
DECLARE_DO_FUN( do_dump		);
DECLARE_DO_FUN(	do_east		);
DECLARE_DO_FUN(	do_eat		);
DECLARE_DO_FUN(	do_echo		);
DECLARE_DO_FUN( do_esay		);
DECLARE_DO_FUN( do_estimate	);
DECLARE_DO_FUN(	do_lgecho	);
DECLARE_DO_FUN(	do_emote	);
DECLARE_DO_FUN( do_enter	);
DECLARE_DO_FUN( do_envenom	);
DECLARE_DO_FUN( do_excolour	);
DECLARE_DO_FUN( do_eyefocus	);
DECLARE_DO_FUN( do_wildcraft	);
DECLARE_DO_FUN( do_cards	);
DECLARE_DO_FUN(	do_equipment	);
DECLARE_DO_FUN(	do_examine	);
DECLARE_DO_FUN( do_exdesc	);
DECLARE_DO_FUN(	do_exits	);
DECLARE_DO_FUN( do_exsanguinate	);
DECLARE_DO_FUN(	do_fill		);
DECLARE_DO_FUN( do_feint	);
DECLARE_DO_FUN( do_finquiry	);
DECLARE_DO_FUN( do_flag		);
DECLARE_DO_FUN(	do_flee		);
DECLARE_DO_FUN( do_flist	);
DECLARE_DO_FUN( do_factions );
DECLARE_DO_FUN(	do_follow	);
DECLARE_DO_FUN(	do_force	);
DECLARE_DO_FUN( do_fly		);
DECLARE_DO_FUN( do_showtracks	);
DECLARE_DO_FUN( do_showmem	);
DECLARE_DO_FUN( do_contact_agents);
DECLARE_DO_FUN( do_freetell     );
DECLARE_DO_FUN(	do_freeze	);
DECLARE_DO_FUN( do_fsave	);
DECLARE_DO_FUN( do_gag          );
DECLARE_DO_FUN( do_gain		);
DECLARE_DO_FUN(	do_get		);
DECLARE_DO_FUN(	do_give		);
DECLARE_DO_FUN(	do_goto		);
DECLARE_DO_FUN(	do_shift	);
DECLARE_DO_FUN( do_grantmercy	);
DECLARE_DO_FUN( do_greet	);
DECLARE_DO_FUN(	do_group	);
DECLARE_DO_FUN(	do_groupadd	);
DECLARE_DO_FUN( do_groups	);
DECLARE_DO_FUN(	do_gtell	);
DECLARE_DO_FUN(	do_cant		);
DECLARE_DO_FUN( do_guild    	);
DECLARE_DO_FUN( do_encamp       );
DECLARE_DO_FUN( do_focus	);
DECLARE_DO_FUN( do_unfocus	);
DECLARE_DO_FUN( do_harmonize	);
DECLARE_DO_FUN( do_heal		);
DECLARE_DO_FUN(	do_help		);
DECLARE_DO_FUN(	do_hide		);
DECLARE_DO_FUN( do_nopk		);
DECLARE_DO_FUN( do_showdam      );
DECLARE_DO_FUN( do_hostlist	);
DECLARE_DO_FUN(	do_holylight	);
DECLARE_DO_FUN( do_notify	);
DECLARE_DO_FUN(	do_idea		);
DECLARE_DO_FUN( do_idle		);
DECLARE_DO_FUN( do_areaupdate	);
DECLARE_DO_FUN(	do_immtalk	);
DECLARE_DO_FUN(	do_imptalk	);
DECLARE_DO_FUN( do_incognito	);
DECLARE_DO_FUN( do_clantalk	);
DECLARE_DO_FUN( do_corpsewhere);
DECLARE_DO_FUN( do_druidtalk    );
DECLARE_DO_FUN( do_imotd	);
DECLARE_DO_FUN( do_inspect	);
DECLARE_DO_FUN(	do_inventory	);
DECLARE_DO_FUN(	do_invis	);
DECLARE_DO_FUN(	do_kick		);
DECLARE_DO_FUN(	do_kill		);
DECLARE_DO_FUN( do_kprompt	);
DECLARE_DO_FUN( do_land		);
DECLARE_DO_FUN( do_languages	);
DECLARE_DO_FUN(	do_list		);
DECLARE_DO_FUN( do_load		);
DECLARE_DO_FUN(	do_lock		);
DECLARE_DO_FUN(	do_log		);
DECLARE_DO_FUN(	do_look		);
DECLARE_DO_FUN( do_lore		);
DECLARE_DO_FUN(	do_memory	);
DECLARE_DO_FUN( do_mercy	);
DECLARE_DO_FUN( do_mindlink	);
DECLARE_DO_FUN(	do_mobcount	);
DECLARE_DO_FUN(	do_mfind	);
DECLARE_DO_FUN( do_mlist	);
DECLARE_DO_FUN(	do_mload	);
DECLARE_DO_FUN( do_morph        );
DECLARE_DO_FUN( do_mount	);
DECLARE_DO_FUN( do_mrefresh	);
DECLARE_DO_FUN( do_mimic	);
DECLARE_DO_FUN(	do_mset		);
DECLARE_DO_FUN(	do_mstat	);
DECLARE_DO_FUN(	do_mwhere	);
DECLARE_DO_FUN( do_motd		);
DECLARE_DO_FUN( do_multisoc     );
DECLARE_DO_FUN(	do_murde	);
DECLARE_DO_FUN(	do_murder	);
DECLARE_DO_FUN( do_music	);
DECLARE_DO_FUN( do_newlock	);
DECLARE_DO_FUN( do_oldscore	);
DECLARE_DO_FUN( do_newbietalk	);
DECLARE_DO_FUN( do_newwho	);
DECLARE_DO_FUN( do_newwhois	);
DECLARE_DO_FUN( do_news		);
DECLARE_DO_FUN( do_oath		);
DECLARE_DO_FUN( do_nochannels	);
DECLARE_DO_FUN(	do_noemote	);
DECLARE_DO_FUN( do_nofollow	);
DECLARE_DO_FUN( do_nolag	);
DECLARE_DO_FUN( do_noloot	);
DECLARE_DO_FUN(	do_north	);
DECLARE_DO_FUN(	do_noshout	);
DECLARE_DO_FUN( do_nosummon	);
DECLARE_DO_FUN( do_noyell	);
DECLARE_DO_FUN( do_camoublind   );
DECLARE_DO_FUN( do_wildmovement );
DECLARE_DO_FUN(	do_note		);
DECLARE_DO_FUN(	do_noooc	);
DECLARE_DO_FUN(	do_notell	);
DECLARE_DO_FUN( do_objcount	);
DECLARE_DO_FUN( do_obscure	);
DECLARE_DO_FUN(	do_ofind	);
DECLARE_DO_FUN( do_olist	);
DECLARE_DO_FUN(	do_oload	);
DECLARE_DO_FUN( do_oocoff       );
DECLARE_DO_FUN( do_ooctell      );
DECLARE_DO_FUN( do_open         );
DECLARE_DO_FUN( do_opstat       );
DECLARE_DO_FUN(	do_order	);
DECLARE_DO_FUN(	do_oset		);
DECLARE_DO_FUN(	do_ostat	);
DECLARE_DO_FUN( do_outfit	);
DECLARE_DO_FUN( do_olimit	);
DECLARE_DO_FUN( do_owhere	);
DECLARE_DO_FUN(	do_pardon	);
DECLARE_DO_FUN(	do_password	);
DECLARE_DO_FUN(	do_peace	);
DECLARE_DO_FUN( do_pecho	);
DECLARE_DO_FUN( do_penalty	);
DECLARE_DO_FUN( do_permban	);
DECLARE_DO_FUN( do_permexdesc	);
DECLARE_DO_FUN(	do_pick		);
DECLARE_DO_FUN(	do_relock	);
DECLARE_DO_FUN( do_play		);
DECLARE_DO_FUN( do_pmote	);
DECLARE_DO_FUN(	do_pose		);
DECLARE_DO_FUN( do_pour		);
DECLARE_DO_FUN(	do_practice	);
DECLARE_DO_FUN( do_pray         );
DECLARE_DO_FUN( do_prefi	);
DECLARE_DO_FUN( do_prefix	);
DECLARE_DO_FUN( do_unbrand	);
DECLARE_DO_FUN( do_prompt	);
DECLARE_DO_FUN( do_puerto	);
DECLARE_DO_FUN( do_defaultprompt);
DECLARE_DO_FUN( do_battlecry	);
DECLARE_DO_FUN( do_snoopprotect	);
DECLARE_DO_FUN(	do_purge	);
DECLARE_DO_FUN(	do_put		);
DECLARE_DO_FUN(	do_quaff	);
DECLARE_DO_FUN( do_question	);
DECLARE_DO_FUN(	do_qui		);
// DECLARE_DO_FUN( do_quiet	);
DECLARE_DO_FUN(	do_quit		);
DECLARE_DO_FUN( do_read		);
DECLARE_DO_FUN(	do_emitstats);
DECLARE_DO_FUN(	do_reboo	);
DECLARE_DO_FUN(	do_reboot	);
DECLARE_DO_FUN(	do_reb00t	);
DECLARE_DO_FUN(	do_causesegv	);
DECLARE_DO_FUN(	do_spiritrecall	);
DECLARE_DO_FUN( do_rangermenu   );
DECLARE_DO_FUN(	do_recall	);
DECLARE_DO_FUN(	do_recho	);
DECLARE_DO_FUN(	do_recite	);
DECLARE_DO_FUN(	do_remove	);
DECLARE_DO_FUN(	do_rent		);
DECLARE_DO_FUN( do_repair	);
DECLARE_DO_FUN( do_replay	);
DECLARE_DO_FUN(	do_reply	);
DECLARE_DO_FUN(	do_oocreply	);
DECLARE_DO_FUN(	do_report	);
DECLARE_DO_FUN(	do_rescue	);
DECLARE_DO_FUN(	do_rest		);
DECLARE_DO_FUN(	do_restore	);
DECLARE_DO_FUN( do_retainer	);
DECLARE_DO_FUN( do_retreat	);
DECLARE_DO_FUN(	do_return	);
DECLARE_DO_FUN(	do_relinquish	);
DECLARE_DO_FUN( do_revert	);
DECLARE_DO_FUN( do_rlist	);
DECLARE_DO_FUN( do_rnote	);
DECLARE_DO_FUN( do_room		);
DECLARE_DO_FUN(	do_rset		);
DECLARE_DO_FUN(	do_rstat	);
DECLARE_DO_FUN( do_rules	);
DECLARE_DO_FUN(	do_sacrifice	);
DECLARE_DO_FUN(	do_save		);
DECLARE_DO_FUN(	do_say		);
DECLARE_DO_FUN( do_scan         );
DECLARE_DO_FUN(	do_score	);
DECLARE_DO_FUN( do_scroll	);
DECLARE_DO_FUN(	do_sell		);
DECLARE_DO_FUN(	do_returnitem);
DECLARE_DO_FUN( do_set		);
DECLARE_DO_FUN( do_shieldbash	);
DECLARE_DO_FUN( do_shieldcover  );
DECLARE_DO_FUN( do_show		);
DECLARE_DO_FUN(	do_showdata     );
DECLARE_DO_FUN(	do_shutdow	);
DECLARE_DO_FUN(	do_shutdown	);
DECLARE_DO_FUN( do_sing		);
DECLARE_DO_FUN( do_sit		);
DECLARE_DO_FUN( do_slog		);
DECLARE_DO_FUN( do_flank	);
DECLARE_DO_FUN( do_skills	);
DECLARE_DO_FUN( do_forms	);
DECLARE_DO_FUN(	do_sla		);
DECLARE_DO_FUN(	do_fwap		);
DECLARE_DO_FUN(	do_slay		);
DECLARE_DO_FUN(	do_rename	);
DECLARE_DO_FUN(	do_sleep	);
DECLARE_DO_FUN(	do_lightsleep	);
DECLARE_DO_FUN(	do_slookup	);
DECLARE_DO_FUN( do_bludgeon	);
DECLARE_DO_FUN( do_vitalstrike	);
DECLARE_DO_FUN( do_csnoop	);
DECLARE_DO_FUN( do_smi          );
DECLARE_DO_FUN( do_smite        );
DECLARE_DO_FUN( do_smote	);
DECLARE_DO_FUN(	do_sneak	);
DECLARE_DO_FUN(	do_snoop	);
DECLARE_DO_FUN( do_songs	);
DECLARE_DO_FUN(	do_flipbit	);
DECLARE_DO_FUN(	do_showbit	);
DECLARE_DO_FUN( do_socials	);
DECLARE_DO_FUN(	do_south	);
DECLARE_DO_FUN( do_sockets	);
DECLARE_DO_FUN( do_speak	);
DECLARE_DO_FUN( do_spells	);
DECLARE_DO_FUN(	do_split	);
DECLARE_DO_FUN(	do_sset		);
DECLARE_DO_FUN(	do_stand	);
DECLARE_DO_FUN( do_wstat	);
DECLARE_DO_FUN(	do_biaslist	);
DECLARE_DO_FUN(	do_version	);
DECLARE_DO_FUN(	do_showlimits	);
DECLARE_DO_FUN( do_stat		);
DECLARE_DO_FUN( do_fstat	);
DECLARE_DO_FUN(	do_steal	);
DECLARE_DO_FUN(	do_plant	);
DECLARE_DO_FUN(	do_cutpurse	);
DECLARE_DO_FUN( do_story	);
DECLARE_DO_FUN( do_string	);
DECLARE_DO_FUN( do_sui          );
DECLARE_DO_FUN( do_suicide      );
DECLARE_DO_FUN(	do_switch	);
/*DECLARE_DO_FUN( do_tail		);*/
DECLARE_DO_FUN(	do_tell		);
DECLARE_DO_FUN( do_test		);
DECLARE_DO_FUN( do_throw	);
DECLARE_DO_FUN( do_dart	);
DECLARE_DO_FUN( do_think	);
DECLARE_DO_FUN(	do_time		);
DECLARE_DO_FUN(	do_title	);
DECLARE_DO_FUN(	do_train	);
DECLARE_DO_FUN( do_trait	);
DECLARE_DO_FUN( do_translate	);
DECLARE_DO_FUN(	do_transfer	);
DECLARE_DO_FUN( do_trip		);
DECLARE_DO_FUN(	do_trust	);
DECLARE_DO_FUN(	do_typo		);
DECLARE_DO_FUN( do_unalias	);
DECLARE_DO_FUN(	do_unlock	);
DECLARE_DO_FUN( do_unread	);
DECLARE_DO_FUN(	do_up		);
DECLARE_DO_FUN(	do_value	);
DECLARE_DO_FUN(	do_visible	);
DECLARE_DO_FUN( do_violate	);
DECLARE_DO_FUN( do_vnum		);
DECLARE_DO_FUN( do_vnumlist     );
DECLARE_DO_FUN(	do_wake		);
DECLARE_DO_FUN( do_waylay	);
DECLARE_DO_FUN( do_swordrepair );
DECLARE_DO_FUN( do_pommel	);
DECLARE_DO_FUN( do_rout	);
DECLARE_DO_FUN( do_pummel	);
DECLARE_DO_FUN( do_uppercut	);
DECLARE_DO_FUN( do_hew		);
DECLARE_DO_FUN( do_nerve	);
DECLARE_DO_FUN( do_caltraps	);
DECLARE_DO_FUN( do_garrote	);
DECLARE_DO_FUN( do_setambush    );
DECLARE_DO_FUN( do_submissionhold);
DECLARE_DO_FUN( do_offhanddisarm);
DECLARE_DO_FUN( do_inertialstrike);
DECLARE_DO_FUN( do_shockwave	);
DECLARE_DO_FUN( do_ram		);
DECLARE_DO_FUN( do_fury		);
DECLARE_DO_FUN( do_rage		);
DECLARE_DO_FUN( do_warcry	);
DECLARE_DO_FUN( do_fetish	);
DECLARE_DO_FUN( do_boneshatter	);
DECLARE_DO_FUN( do_lunge	);
DECLARE_DO_FUN( do_forcedmarch	);
DECLARE_DO_FUN( do_scouting	);
DECLARE_DO_FUN( do_setsnare     );
DECLARE_DO_FUN( do_rally	);
DECLARE_DO_FUN( do_maul		);
DECLARE_DO_FUN( do_cover	);
DECLARE_DO_FUN( do_guard	);
DECLARE_DO_FUN( do_readiness	);
DECLARE_DO_FUN( do_agility	);
DECLARE_DO_FUN( do_wariness	);
DECLARE_DO_FUN( do_bandage	);
DECLARE_DO_FUN( do_drive	);
DECLARE_DO_FUN( do_strip	);
DECLARE_DO_FUN( do_entangle	);
DECLARE_DO_FUN( do_grip		);
DECLARE_DO_FUN( do_cross	);
DECLARE_DO_FUN( do_lash		);
DECLARE_DO_FUN( do_sortie       );
DECLARE_DO_FUN( do_flay         );
DECLARE_DO_FUN( do_choke	);
DECLARE_DO_FUN( do_cleave	);
DECLARE_DO_FUN( do_batter	);
DECLARE_DO_FUN( do_bind		);
DECLARE_DO_FUN( do_gash		);
DECLARE_DO_FUN( do_sweep	);
DECLARE_DO_FUN( do_escape	);
DECLARE_DO_FUN( do_intimidate	);
DECLARE_DO_FUN( do_request	);
DECLARE_DO_FUN( do_release	);
DECLARE_DO_FUN( do_befriend	);
DECLARE_DO_FUN( do_tame		);
DECLARE_DO_FUN( do_findwater	);
DECLARE_DO_FUN( do_callanimal	);
DECLARE_DO_FUN( do_taint	);
DECLARE_DO_FUN( do_write	);
DECLARE_DO_FUN( do_craftdart	);
DECLARE_DO_FUN( do_prepare	);
DECLARE_DO_FUN( do_tan		);
DECLARE_DO_FUN( do_findherbs	);
DECLARE_DO_FUN( do_sixthsense	);
DECLARE_DO_FUN( do_hooded       );
DECLARE_DO_FUN( do_perception	);
DECLARE_DO_FUN( do_blindingdust	);
DECLARE_DO_FUN( do_blindingcloud);
DECLARE_DO_FUN( do_flashpowder	);
DECLARE_DO_FUN( do_dive		);
//DECLARE_DO_FUN( do_cloak	);
DECLARE_DO_FUN( do_investigate	);
DECLARE_DO_FUN( do_sentry	);
DECLARE_DO_FUN( do_stash	);
DECLARE_DO_FUN( do_search	);
DECLARE_DO_FUN( do_ambush	);
DECLARE_DO_FUN( do_camouflage	);
DECLARE_DO_FUN( do_sharp_vision	);
DECLARE_DO_FUN( do_poultice	);
DECLARE_DO_FUN( do_herbalmedicine);
DECLARE_DO_FUN( do_loot		);
DECLARE_DO_FUN( do_trap		);
DECLARE_DO_FUN( do_daggertrap	);
DECLARE_DO_FUN( do_bolo		);
DECLARE_DO_FUN( do_findcover	);
DECLARE_DO_FUN( do_perform	);
DECLARE_DO_FUN( do_tripwire	);
DECLARE_DO_FUN( do_track	);
DECLARE_DO_FUN( do_pursue	);
DECLARE_DO_FUN( do_conceal	);
DECLARE_DO_FUN( do_sleeve	);
DECLARE_DO_FUN( do_hamstring	);
DECLARE_DO_FUN( do_slice	);
DECLARE_DO_FUN( do_grapple	);
DECLARE_DO_FUN( do_trophy	);
DECLARE_DO_FUN( do_nightvision	);
DECLARE_DO_FUN( do_listen	);
DECLARE_DO_FUN( do_drag		);
DECLARE_DO_FUN( do_surpriseattack );
DECLARE_DO_FUN( do_record	);
DECLARE_DO_FUN( do_runicmessage );
DECLARE_DO_FUN( do_inquire	);
DECLARE_DO_FUN( do_disguise	);
DECLARE_DO_FUN( do_diagnose     );
DECLARE_DO_FUN( do_detecthidden	);
DECLARE_DO_FUN( do_songbook	);
DECLARE_DO_FUN( do_ensnare	);
DECLARE_DO_FUN( do_impale	);
DECLARE_DO_FUN( do_gouge	);
DECLARE_DO_FUN( do_savagery	);
DECLARE_DO_FUN( do_aggression	);
DECLARE_DO_FUN( do_fortitude	);
DECLARE_DO_FUN( do_legsweep	);
DECLARE_DO_FUN( do_shoot        );
DECLARE_DO_FUN( do_withdraw	);
DECLARE_DO_FUN( do_pugil	);
DECLARE_DO_FUN( do_twirl	);
DECLARE_DO_FUN( do_undeny	);
DECLARE_DO_FUN(	do_wear		);
DECLARE_DO_FUN( do_noweather	);
DECLARE_DO_FUN(	do_weather	);
DECLARE_DO_FUN(	do_west		);
DECLARE_DO_FUN(	do_where	);
DECLARE_DO_FUN( do_criminal	);
DECLARE_DO_FUN(	do_who		);
DECLARE_DO_FUN( do_whois	);
DECLARE_DO_FUN(	do_wimpy	);
DECLARE_DO_FUN( do_withdrawal	);
DECLARE_DO_FUN(	do_wizhelp	);
DECLARE_DO_FUN(	do_rcheck	);
DECLARE_DO_FUN(	do_cgen		);
DECLARE_DO_FUN(	do_materials	);
DECLARE_DO_FUN( do_vanish	);
DECLARE_DO_FUN(	do_wizlock	);
DECLARE_DO_FUN( do_wizlist	);
DECLARE_DO_FUN( do_wiznet	);
DECLARE_DO_FUN( do_wiztalk      );
DECLARE_DO_FUN( do_worth	);
DECLARE_DO_FUN(	do_yell		);
DECLARE_DO_FUN(	do_char_yell	);
DECLARE_DO_FUN(	do_zap		);
DECLARE_DO_FUN( old_do_nock         );
DECLARE_OBJ_DO_FUN( do_nock         );
DECLARE_DO_FUN(	do_identifyowner);
DECLARE_DO_FUN( do_zecho	);
DECLARE_DO_FUN( do_whodata	);

DECLARE_DO_FUN( do_badscan	);
DECLARE_DO_FUN( do_approve	);

DECLARE_DO_FUN( do_olc		);
DECLARE_DO_FUN( do_asave	);
DECLARE_DO_FUN( do_alist	);
DECLARE_DO_FUN( do_resets	);
DECLARE_DO_FUN( do_redit	);
DECLARE_DO_FUN( do_aedit	);
DECLARE_DO_FUN( do_medit	);
DECLARE_DO_FUN( do_oedit	);
DECLARE_DO_FUN( do_hedit	);
DECLARE_DO_FUN( do_fedit	);
DECLARE_DO_FUN( do_erase	);
DECLARE_DO_FUN( do_inscribe	);
DECLARE_DO_FUN( do_vsearch	);

/* Mobile program specific commands */
DECLARE_DO_FUN( do_mpasound     );
DECLARE_DO_FUN( do_mpat         );
DECLARE_DO_FUN( do_mpecho       );
DECLARE_DO_FUN( do_mpzecho      );
DECLARE_DO_FUN( do_mpgecho	);
DECLARE_DO_FUN( do_mpechoaround );
DECLARE_DO_FUN( do_mpechoat     );
DECLARE_DO_FUN( do_mpforce      );
DECLARE_DO_FUN( do_mplock	);
DECLARE_DO_FUN( do_mpunlock	);
DECLARE_DO_FUN( do_mpslay       );
DECLARE_DO_FUN( do_mpxp	        );
DECLARE_DO_FUN( do_mpwizi       );
DECLARE_DO_FUN( do_mpunwizi	);
DECLARE_DO_FUN( do_mpseewizi    );
DECLARE_DO_FUN( do_mpunseewizi  );
DECLARE_DO_FUN( do_mptrack	);
DECLARE_DO_FUN( do_mptrackstep	);
DECLARE_DO_FUN( do_mpdamage     );
DECLARE_DO_FUN( do_mpdamtype    );
DECLARE_DO_FUN( do_mpgoto       );
DECLARE_DO_FUN( do_mpsetskilled );
DECLARE_DO_FUN( do_mpflag       );
DECLARE_DO_FUN( do_mpstring	);
DECLARE_DO_FUN( do_mpunsetskilled);
DECLARE_DO_FUN( do_mpjunk       );
DECLARE_DO_FUN( do_mpkill       );
DECLARE_DO_FUN( do_mpwander     );
DECLARE_DO_FUN( do_mprangekill  );
DECLARE_DO_FUN( do_mptrap	);
DECLARE_DO_FUN( do_mpbrand	);
DECLARE_DO_FUN( do_mpmload      );
DECLARE_DO_FUN( do_mpoload      );
DECLARE_DO_FUN( do_mptellimm    );
DECLARE_DO_FUN( do_mppurge      );
DECLARE_DO_FUN( do_mpget	);
DECLARE_DO_FUN( do_mpset        );
DECLARE_DO_FUN( do_mpbitset     );
DECLARE_DO_FUN( do_mpsilverset	);
DECLARE_DO_FUN( do_mpgrant	);
DECLARE_DO_FUN( do_mpfocus	);
DECLARE_DO_FUN( do_mpunfocus	);
DECLARE_DO_FUN( do_mpstopfollow );
DECLARE_DO_FUN( do_mpremember	);
DECLARE_DO_FUN( do_mpforget	);
DECLARE_DO_FUN( do_mpmemvset    );
DECLARE_DO_FUN( do_mpmemvup     );
DECLARE_DO_FUN( do_mpmemvdown   );
DECLARE_DO_FUN( do_mpmemvrand   );
DECLARE_DO_FUN( do_mpvalueset   );
DECLARE_DO_FUN( do_mpvalueup    );
DECLARE_DO_FUN( do_mpvaluedown  );
DECLARE_DO_FUN( do_mpvaluerand  );
DECLARE_DO_FUN( do_mpcast       );
DECLARE_DO_FUN( do_mproomcmd    );
DECLARE_DO_FUN( do_mptrigger    );
DECLARE_DO_FUN( do_mpinterpret  );
DECLARE_DO_FUN( do_mpaddaffect  );
DECLARE_DO_FUN( do_mproomaffect );
DECLARE_DO_FUN( do_mpknockout   );
DECLARE_DO_FUN( do_mptentacle	);
DECLARE_DO_FUN( do_mpvaultprep  );
DECLARE_DO_FUN( do_mpvaultdrop  );
DECLARE_DO_FUN( do_mpvaultshow  );
DECLARE_DO_FUN( do_mpvaultgive  );
DECLARE_DO_FUN( do_mpabishai	);
DECLARE_DO_FUN( do_mpgharku	);
DECLARE_DO_FUN( do_mpisetaton	);
DECLARE_DO_FUN( do_mpagduk	);
DECLARE_DO_FUN( do_mppricina	);
DECLARE_DO_FUN( do_mpkhamurn	);
DECLARE_DO_FUN( do_mporzub	);
DECLARE_DO_FUN( do_mpchagrob	);
DECLARE_DO_FUN( do_mpbarkjaset	);
DECLARE_DO_FUN( do_mpbarkjayes	);
DECLARE_DO_FUN( do_mpbittrigger	);
DECLARE_DO_FUN( do_mpmasstrigger);
DECLARE_DO_FUN( do_mpremaffect );
DECLARE_DO_FUN( do_mprevolt	);
DECLARE_DO_FUN( do_mpescape	);
DECLARE_DO_FUN( do_mpstat       );
DECLARE_DO_FUN( do_mpstatdown   );
DECLARE_DO_FUN( do_mpstatup     );
DECLARE_DO_FUN( do_mptransfer   );
DECLARE_DO_FUN( do_mploot   	);
DECLARE_DO_FUN( do_mplag	);
DECLARE_DO_FUN( do_mpslotremove	);
DECLARE_DO_FUN( do_mpslotpurge	);
DECLARE_DO_FUN( do_mpsetskills	);

DECLARE_DO_FUN( do_rpstat	);

DECLARE_DO_FUN( do_xmusic	);
DECLARE_DO_FUN( do_playmusic	);

// Alchemists
DECLARE_DO_FUN( do_mix		);
DECLARE_DO_FUN( do_brew		);
DECLARE_DO_FUN( do_make		);
DECLARE_DO_FUN( do_pitch	);
DECLARE_DO_FUN( do_applyoil	);
DECLARE_DO_FUN( do_applybarbs	);
DECLARE_DO_FUN( do_applypoison	);
DECLARE_DO_FUN( do_distill      );
DECLARE_DO_FUN( do_pulverize    );
DECLARE_DO_FUN( do_reforge      );
DECLARE_DO_FUN( do_boil         );
DECLARE_DO_FUN( do_dissolve     );
DECLARE_DO_FUN( do_dilute       );
DECLARE_DO_FUN( do_delayreaction);
DECLARE_DO_FUN( do_animategolem );
DECLARE_DO_FUN( do_dye 		);
DECLARE_DO_FUN( do_discernmagic );
DECLARE_DO_FUN( do_finditems	);
DECLARE_DO_FUN( do_harrudimtalc );
DECLARE_DO_FUN( do_smokescreen  );
DECLARE_DO_FUN( do_rynathsbrew	);
DECLARE_DO_FUN( do_alchemicstone);
DECLARE_DO_FUN( do_createwand	);
DECLARE_DO_FUN( do_colorlist	);
DECLARE_DO_FUN( do_createhomonculus );
// End alchemists

// Fire Scholars
DECLARE_DO_FUN( do_firedancer	);
DECLARE_DO_FUN( do_incinerate	);
DECLARE_DO_FUN( do_bloodpyre	);

// Spirit Scholars
DECLARE_DO_FUN(do_weavesense);
DECLARE_DO_FUN(do_chantlitany);
DECLARE_DO_FUN(do_radiateaura);
DECLARE_DO_FUN(do_triumphantshout);
DECLARE_DO_FUN(do_assesssoul);
DECLARE_DO_FUN(do_sensedreamers);
DECLARE_DO_FUN(do_relocate);

// Water Scholars
DECLARE_DO_FUN(do_somaticarts);

// Air Scholars
DECLARE_DO_FUN(do_shockcraft);
DECLARE_DO_FUN(do_phantasm);
DECLARE_DO_FUN(do_deliver);

// Earth Scholars
DECLARE_DO_FUN(do_adamantineinvocation);
DECLARE_DO_FUN(do_carve);
DECLARE_DO_FUN(do_rune);
DECLARE_DO_FUN(do_constructwaterwheel);
DECLARE_DO_FUN(do_forgeweapon);
DECLARE_DO_FUN(do_nameweapon);
DECLARE_DO_FUN(do_wakenstone);
DECLARE_DO_FUN(do_clockworksoul);

// Void Scholars
DECLARE_DO_FUN(do_fellpurpose);
DECLARE_DO_FUN(do_repossess);
DECLARE_DO_FUN(do_corpsesense);

// Chirurgeon
DECLARE_DO_FUN(do_cauterize );
DECLARE_DO_FUN(do_whipstitch);
DECLARE_DO_FUN(do_anesthetize);
DECLARE_DO_FUN(do_animate_dead);

DECLARE_ODO_FUN( do_opasound     );
DECLARE_ODO_FUN( do_opat         );
DECLARE_ODO_FUN( do_opfocus	 );
DECLARE_ODO_FUN( do_opunfocus	);
DECLARE_ODO_FUN( do_opecho       );
DECLARE_ODO_FUN( do_opecho_fight );
DECLARE_ODO_FUN( do_opechoaround );
DECLARE_ODO_FUN( do_opechoat     );
DECLARE_ODO_FUN( do_opforce      );
DECLARE_ODO_FUN( do_opxp        );
DECLARE_ODO_FUN( do_opbitset	);
DECLARE_ODO_FUN( do_opcast      );
DECLARE_ODO_FUN( do_opcastoff   );
DECLARE_ODO_FUN( do_opgoto      );
DECLARE_ODO_FUN( do_opjunk      );
DECLARE_ODO_FUN( do_opinterpret );
DECLARE_ODO_FUN( do_opflag	);
DECLARE_ODO_FUN( do_opmload     );
DECLARE_ODO_FUN( do_opmset      );
DECLARE_ODO_FUN( do_opoload     );
DECLARE_ODO_FUN( do_oposet      );
DECLARE_ODO_FUN( do_opstring	);
DECLARE_ODO_FUN( do_oppurge     );
DECLARE_ODO_FUN( do_oprset      );
DECLARE_ODO_FUN( do_opslotremove);
DECLARE_ODO_FUN( do_opslotpurge );
DECLARE_ODO_FUN( do_opvalueset  );
DECLARE_ODO_FUN( do_opvalueup   );
DECLARE_ODO_FUN( do_opvaluedown );
DECLARE_ODO_FUN( do_opvaluerand );
DECLARE_ODO_FUN( do_opset       );
DECLARE_ODO_FUN( do_opgrant     );
DECLARE_ODO_FUN( do_opdamage    );
DECLARE_ODO_FUN( do_opzap       );
DECLARE_ODO_FUN( do_opslay      );
DECLARE_ODO_FUN( do_oplag       );
DECLARE_ODO_FUN( do_opsset      );
DECLARE_ODO_FUN( do_opstatdown  );
DECLARE_ODO_FUN( do_opstatup    );
DECLARE_ODO_FUN( do_optransfer  );
DECLARE_ODO_FUN( do_opaddaffect );
DECLARE_ODO_FUN( do_opremaffect );
DECLARE_ODO_FUN( do_opverbstop	);



DECLARE_PRO_FUN( prog_rumor);
DECLARE_PRO_FUN( prog_addrumor);
DECLARE_PRO_FUN( prog_math );
DECLARE_PRO_FUN( prog_dice );
DECLARE_PRO_FUN( prog_knockout );
DECLARE_PRO_FUN( prog_grant );
DECLARE_PRO_FUN( prog_hitdamage );
DECLARE_PRO_FUN( prog_roomaffect );
DECLARE_PRO_FUN( prog_addaffect );
DECLARE_PRO_FUN( prog_addroomaffect );
DECLARE_PRO_FUN( prog_asound );
DECLARE_PRO_FUN( prog_wander );
DECLARE_PRO_FUN( prog_brand );
DECLARE_PRO_FUN( prog_slay );
DECLARE_PRO_FUN( prog_statup );
DECLARE_PRO_FUN( prog_statdown );
DECLARE_PRO_FUN( prog_silverset );
DECLARE_PRO_FUN( prog_kill );
DECLARE_PRO_FUN( prog_rangekill );
DECLARE_PRO_FUN( prog_junk );
DECLARE_PRO_FUN( prog_zecho );
DECLARE_PRO_FUN( prog_gecho );
DECLARE_PRO_FUN( prog_echoaround );
DECLARE_PRO_FUN( prog_echoat );
DECLARE_PRO_FUN( prog_echo );
DECLARE_PRO_FUN( prog_echo_fight );
DECLARE_PRO_FUN( prog_mload );
DECLARE_PRO_FUN( prog_tellimm );
DECLARE_PRO_FUN( prog_oload );
DECLARE_PRO_FUN( prog_purge );
DECLARE_PRO_FUN( prog_slotremove );
DECLARE_PRO_FUN( prog_slotpurge );
DECLARE_PRO_FUN( prog_setskilled );
DECLARE_PRO_FUN( prog_unsetskilled );
DECLARE_PRO_FUN( prog_goto );
DECLARE_PRO_FUN( prog_at );
DECLARE_PRO_FUN( prog_lag );
DECLARE_PRO_FUN( prog_setdata );
DECLARE_PRO_FUN( prog_nextdata );
DECLARE_PRO_FUN( prog_adddata );
DECLARE_PRO_FUN( prog_deletedata );
DECLARE_PRO_FUN( prog_transfer );
DECLARE_PRO_FUN( prog_trackstep );
DECLARE_PRO_FUN( prog_track );
DECLARE_PRO_FUN( prog_wizi );
DECLARE_PRO_FUN( prog_unwizi );
DECLARE_PRO_FUN( prog_seewizi );
DECLARE_PRO_FUN( prog_unseewizi );
DECLARE_PRO_FUN( prog_xp );
DECLARE_PRO_FUN( prog_force );
DECLARE_PRO_FUN( prog_exit	);
DECLARE_PRO_FUN( prog_interpret );
DECLARE_PRO_FUN( prog_valueup );
DECLARE_PRO_FUN( prog_valuedown );
DECLARE_PRO_FUN( prog_valuerand );
DECLARE_PRO_FUN( prog_valueset );
DECLARE_PRO_FUN( prog_setexit);
DECLARE_PRO_FUN( prog_verbstop );
DECLARE_PRO_FUN( prog_focus );
DECLARE_PRO_FUN( prog_unfocus );
DECLARE_PRO_FUN( prog_bitset );
DECLARE_PRO_FUN( prog_zap );
DECLARE_PRO_FUN( prog_tentacle );
DECLARE_PRO_FUN( prog_vaultdrop );
DECLARE_PRO_FUN( prog_revolt );
DECLARE_PRO_FUN( prog_escape );
DECLARE_PRO_FUN( prog_barkjayes );
DECLARE_PRO_FUN( prog_barkjaset );
DECLARE_PRO_FUN( prog_chagrob );
DECLARE_PRO_FUN( prog_pricina );
DECLARE_PRO_FUN( prog_agduk );
DECLARE_PRO_FUN( prog_isetaton );
DECLARE_PRO_FUN( prog_gharku );
DECLARE_PRO_FUN( prog_orzub );
DECLARE_PRO_FUN( prog_abishai );
DECLARE_PRO_FUN( prog_khamurn );
DECLARE_PRO_FUN( prog_vaultgive );
DECLARE_PRO_FUN( prog_vaultshow 	);
DECLARE_PRO_FUN( prog_vaultprep 	);
DECLARE_PRO_FUN( prog_remaffect 	);
DECLARE_PRO_FUN( prog_cast 		);
DECLARE_PRO_FUN( prog_set 		);
DECLARE_PRO_FUN( prog_trap 		);
DECLARE_PRO_FUN( prog_lock 		);
DECLARE_PRO_FUN( prog_unlock 		);
DECLARE_PRO_FUN( prog_flag 		);
DECLARE_PRO_FUN( prog_string 		);
DECLARE_PRO_FUN( prog_stopfollow 	);
DECLARE_PRO_FUN( prog_loot 		);
DECLARE_PRO_FUN( prog_castoff 		);
DECLARE_PRO_FUN( prog_trigger 		);
DECLARE_PRO_FUN( prog_roomcmd 		);
DECLARE_PRO_FUN( prog_remember 		);
DECLARE_PRO_FUN( prog_forget 		);
DECLARE_PRO_FUN( prog_copyvalues	);
DECLARE_PRO_FUN( prog_memvup 		);
DECLARE_PRO_FUN( prog_memvdown 		);
DECLARE_PRO_FUN( prog_memvrand 		);
DECLARE_PRO_FUN( prog_memvset 		);
DECLARE_PRO_FUN( prog_masstrigger 	);
DECLARE_PRO_FUN( prog_bittrigger 	);
DECLARE_PRO_FUN( prog_unbittrigger	);
DECLARE_PRO_FUN( prog_get 		);
DECLARE_PRO_FUN( prog_damage 		);
DECLARE_PRO_FUN( prog_damtype 		);
DECLARE_PRO_FUN( prog_dammess		);
DECLARE_PRO_FUN( prog_damfrom		);
DECLARE_PRO_FUN( prog_dealdamage	);
DECLARE_PRO_FUN( prog_damfromtype	);
DECLARE_PRO_FUN( prog_permexdesc	);
DECLARE_PRO_FUN( prog_addskill		);
DECLARE_PRO_FUN( prog_removeskill	);
DECLARE_PRO_FUN( prog_stealrandom	);
DECLARE_PRO_FUN( prog_getroomvnum	);
DECLARE_PRO_FUN( prog_remareaaffect	);
DECLARE_PRO_FUN( prog_findpath		);
DECLARE_PRO_FUN( prog_pathstep		);
DECLARE_PRO_FUN( prog_doppel		);
DECLARE_PRO_FUN( prog_disarm		);
DECLARE_PRO_FUN( prog_takecoins		);
DECLARE_PRO_FUN( prog_desc		);
DECLARE_PRO_FUN( prog_loadstring	);
DECLARE_PRO_FUN( prog_resolve	);
DECLARE_PRO_FUN( prog_loaddesc		);
DECLARE_PRO_FUN( prog_concat		);
DECLARE_PRO_FUN( prog_strreplace	);
DECLARE_PRO_FUN( prog_strlen		);
DECLARE_PRO_FUN( prog_addevent		);
DECLARE_PRO_FUN( prog_faction		);
DECLARE_PRO_FUN( prog_follow		);
DECLARE_PRO_FUN( prog_callsub       );

/* demon-related progs */
DECLARE_PRO_FUN( prog_demonid		);
DECLARE_PRO_FUN( prog_demonpcid		);
DECLARE_PRO_FUN( prog_poisonroom	);
DECLARE_PRO_FUN( prog_demonbind		);
DECLARE_PRO_FUN( prog_removehand	);
DECLARE_PRO_FUN( prog_addsymbol		);
DECLARE_PRO_FUN( prog_removesymbol	);
DECLARE_PRO_FUN( prog_addtree		);
DECLARE_PRO_FUN( prog_treefruit		);
DECLARE_PRO_FUN( prog_cursebarkja	);
DECLARE_PRO_FUN( prog_listbounty	);
