extern	CHAR_DATA *	psi_ignore_target;

int	focus_slots	args( ( CHAR_DATA *ch ) );

DECLARE_FOCUS_FUN( abil_concealremains		);
DECLARE_FOCUS_FUN( abil_acuity			);
DECLARE_FOCUS_FUN( abil_celerity		);
DECLARE_FOCUS_FUN( abil_cloak			);
DECLARE_FOCUS_FUN( abil_shadowfist		);
DECLARE_FOCUS_FUN( abil_block_vision		);
DECLARE_FOCUS_FUN( abil_enhance_pain		);
DECLARE_FOCUS_FUN( abil_enhance_reflexes	);
DECLARE_FOCUS_FUN( abil_forget			);
DECLARE_FOCUS_FUN( abil_mindshield		);
DECLARE_FOCUS_FUN( abil_paranoia		);
DECLARE_FOCUS_FUN( abil_reduce_pain		);
DECLARE_FOCUS_FUN( abil_slow_reflexes		);
DECLARE_FOCUS_FUN( abil_symbiont		);
DECLARE_FOCUS_FUN( abil_leech			);
DECLARE_FOCUS_FUN( abil_deflection		);
DECLARE_FOCUS_FUN( abil_levitation		);
DECLARE_FOCUS_FUN( abil_esp			);
DECLARE_FOCUS_FUN( abil_read_thoughts		);
DECLARE_FOCUS_FUN( abil_ignore_pain		);
DECLARE_FOCUS_FUN( abil_detect_life		);
DECLARE_FOCUS_FUN( abil_psychic_block		);
DECLARE_FOCUS_FUN( abil_mind_thrust		);
DECLARE_FOCUS_FUN( abil_psionic_blast		);
DECLARE_FOCUS_FUN( abil_suggestion		);
DECLARE_FOCUS_FUN( abil_sensory_vision		);
DECLARE_FOCUS_FUN( abil_vertigo			);
DECLARE_FOCUS_FUN( abil_foresight		);
DECLARE_FOCUS_FUN( abil_sense_danger		);
DECLARE_FOCUS_FUN( abil_dominance		);
DECLARE_FOCUS_FUN( abil_confusion		);
DECLARE_FOCUS_FUN( abil_prowess			);
DECLARE_FOCUS_FUN( abil_adrenaline_rush		);
DECLARE_FOCUS_FUN( abil_overwhelm		);
DECLARE_FOCUS_FUN( abil_conceal_thoughts	);
DECLARE_FOCUS_FUN( abil_ordered_mind		);
DECLARE_FOCUS_FUN( abil_shove			);
DECLARE_FOCUS_FUN( abil_accelerated_healing	);
DECLARE_FOCUS_FUN( abil_borrow_knowledge	);
